// A10 roster: id, archetype, dominant fill, tree label, colour source.
export const ROSTER = [
	['hack', 'BADGE', '#A46E33', '.hhconfig', 'no brand → hacklang amber'],
	['hadolint', 'SILHOUETTE', '#3E92C6', '.hadolint.yaml', 'no brand → docker blue (Dockerfile-linter rhyme)'],
	['happo', 'SILHOUETTE', '#8C8FA8', '.happo.js', 'no brand → neutral violet-grey'],
	['hardhat', 'SILHOUETTE', '#DFB63F', 'hardhat.config.ts', 'brand #FFF100 → #DFB63F'],
	['harmonix', 'SILHOUETTE', '#4FA8A0', 'harmonix.config.ts', 'no brand → teal'],
	['haxecheckstyle', 'SILHOUETTE', '#D07C2E', 'checkstyle.json', 'Haxe #EA8220 → #D07C2E'],
	['helix', 'SILHOUETTE', '#3E9E7A', '.p4ignore', 'no brand → green-teal'],
	['heroku', 'GLYPH', '#8455CE', 'Procfile.windows', 'brand #430098 ↑ #8455CE'],
	['histoire', 'SILHOUETTE', '#C4608F', 'histoire.config.ts', 'no brand → histoire pink'],
	['homeassistant', 'SILHOUETTE', '#4CB4E0', 'configuration.yaml', 'brand #41BDF5 → #4CB4E0'],
	['host', 'SILHOUETTE', '#8B9AA6', 'hosts', 'no brand → neutral steel'],
	['htmlhint', 'SILHOUETTE', '#C9603E', '.htmlhintrc', 'html hue #E34F26 → #C9603E'],
	['htmlvalidate', 'SILHOUETTE', '#C25A3C', '.htmlvalidate.json', 'html hue #E34F26 → #C25A3C'],
	['hugo', 'BADGE', '#B23F76', 'hugo.toml', 'brand #FF4088 → #B23F76'],
	['husky', 'SILHOUETTE', '#7E96B0', '.huskyrc.json', 'no brand → husky steel-blue'],
	['ifanr-cloud', 'SILHOUETTE', '#5AA8D8', '.mincloudrc', 'no brand → sky blue'],
	['imgbot', 'SILHOUETTE', '#4FA3B4', '.imgbotconfig', 'no brand → teal-blue'],
	['ini', 'GLYPH', '#A8A08C', 'settings.ini', 'no brand → neutral sand'],
	['jasmine', 'SILHOUETTE', '#9B4E93', 'jasmine.json', 'brand #8A4182 → #9B4E93'],
	['jetbrains', 'BADGE', '#A63F53', 'module.iml', 'no brand → JetBrains rose'],
	['jpm', 'SILHOUETTE', '#C87A3C', '.jpmignore', 'no brand → amber'],
	['jshint', 'SILHOUETTE', '#D8C24A', '.jshintrc', 'js hue #F7DF1E → #D8C24A'],
	['jsr', 'BADGE', '#9E8B22', 'jsr.json', 'brand yellow → #9E8B22 (js badge band avoided)'],
	['keystatic', 'SILHOUETTE', '#4E9A9E', 'keystatic.config.ts', 'no brand → teal'],
	['kitchenci', 'SILHOUETTE', '#D9A047', '.kitchen.yml', 'no brand → Chef amber'],
	['kite', 'SILHOUETTE', '#7A7BD4', '.kiteignore', 'no brand → indigo'],
	['kodiak', 'SILHOUETTE', '#9A6E4E', '.kodiak.toml', 'no brand → bear brown'],
	['kubernetes', 'SILHOUETTE', '#3A6BC0', 'k8s.yaml', 'brand #326CE5 → #3A6BC0'],
	['lerna', 'SILHOUETTE', '#9A5FD0', 'lerna.json', 'brand #9333EA → #9A5FD0'],
	['liara', 'BADGE', '#A745B8', 'liara.json', 'no brand → orchid'],
	['licensebat', 'SILHOUETTE', '#8A7FB8', '.licrc', 'no brand → violet-grey'],
	['lintstagedrc', 'SILHOUETTE', '#5FA88E', '.lintstagedrc.json', 'no brand → green-teal'],
	['livekit', 'GLYPH', '#85CED6', 'livekit.yaml', 'brand cyan → #85CED6'],
	['lychee', 'SILHOUETTE', '#C4566B', 'lychee.toml', 'no brand → lychee red'],
	['lynx', 'SILHOUETTE', '#C9A24E', 'lynx.config.ts', 'no brand → lynx gold'],
	['madge', 'SILHOUETTE', '#6E93C9', '.madgerc', 'no brand → slate blue'],
	['mailing', 'SILHOUETTE', '#C4644E', 'mailing.config.json', 'no brand → terracotta'],
	['manifest', 'SILHOUETTE', '#A0968A', 'manifest', 'no brand → neutral stone'],
	['markdoc-config', 'BADGE', '#5FC0B0', 'markdoc.config.js', 'no brand → Markdoc teal'],
	['markdownlint', 'BADGE', '#89B0C2', '.markdownlint.json', 'markdown hue, value-separated'],
	['markdownlint-ignore', 'BADGE', '#5F7E8C', '.markdownlintignore', 'markdownlint dimmed (R3 sibling)'],
	['markuplint', 'GLYPH', '#40A866', '.markuplintrc', 'no brand → green'],
	['mcp', 'SILHOUETTE', '#C4805E', 'mcp.json', 'no brand → warm tan'],
	['mdxlint', 'BADGE', '#5A4E8C', '.mdxlintrc', 'mdx #633EC1 dimmed (R3 sibling)'],
	['mikro-orm', 'GLYPH', '#5566CE', 'mikro-orm.config.ts', 'no brand → indigo'],
	['minecraft-fabric', 'SILHOUETTE', '#B99A6E', 'fabric.mod.json', 'no brand → fabric tan'],
	['mise', 'SILHOUETTE', '#57A76E', 'mise.toml', 'no brand → green'],
	['mondoo', 'SILHOUETTE', '#6E5FD0', 'mondoo.mql.yaml', 'brand purple → #6E5FD0'],
	['monotone', 'BADGE', '#6E6E72', '.mtn-ignore', 'no brand → neutral graphite'],
	['moon', 'SILHOUETTE', '#A79BE8', 'moon.yml', 'brand violet → #A79BE8'],
	['motif', 'SILHOUETTE', '#A88AC4', 'motif.json', 'no brand → mauve'],
	['mypy', 'SILHOUETTE', '#3F7EAE', 'mypy.ini', 'python #3776AB → #3F7EAE'],
	['ndst', 'BADGE', '#94CDD1', 'ndst.yaml', 'no brand → pale teal'],
	['ngrx-entity', 'BADGE', '#B598D8', '.entity', 'brand #BA2BD2 → pale lavender'],
	['nodemon', 'BADGE', '#5FA04E', 'nodemon.json', 'node green #5FA04E (R3 rhyme)'],
	['npmpackagejsonlint', 'BADGE', '#7A2A3E', '.npmpackagejsonlintrc', 'npm red deepened'],
	['nsri', 'GLYPH', '#469E38', '.nsrirc.json', 'no brand → green'],
	['nsri-integrity', 'SILHOUETTE', '#469E38', '.integrity.json', 'nsri green (R3 sibling)'],
	['nuget', 'SILHOUETTE', '#3E6EA8', 'packages.nuspec', 'brand #004880 ↑ #3E6EA8'],
	['nyc', 'SILHOUETTE', '#C74A4A', '.nycrc', 'no brand → Istanbul red'],
	['objidconfig', 'SILHOUETTE', '#9E7FB8', '.objidconfig', 'no brand → violet'],
	['opencode', 'SILHOUETTE', '#AEB3B8', 'opencode.json', 'no brand → neutral silver'],
	['opentofu', 'SILHOUETTE', '#D8B93E', 'main.tofu', 'brand #FFDA18 → #D8B93E'],
	['orval', 'BADGE', '#7A3162', 'orval.config.ts', 'no brand → plum'],
	['oxc', 'GLYPH', '#BA5CD1', '.oxlintrc.json', 'brand violet → #BA5CD1'],
	['packship', 'SILHOUETTE', '#3E92A8', '.packshiprc', 'no brand → harbour blue'],
	['panda', 'SILHOUETTE', '#D8D4CC', 'panda.config.mts', 'brand black+white (R2)'],
	['pandacss', 'SILHOUETTE', '#DFC24E', 'panda.config.ts', 'Panda CSS yellow (R3 twin of panda)'],
	['parcel', 'SILHOUETTE', '#C48A3E', '.parcelrc', 'brand amber → #C48A3E'],
	['payload', 'SILHOUETTE', '#B0B6BE', 'payload.config.ts', 'brand black ↑ #B0B6BE'],
	['pdm', 'GLYPH', '#8482AD', 'pdm.lock', 'no brand → muted indigo'],
	['peeky', 'SILHOUETTE', '#4E9E8E', 'peeky.config.ts', 'no brand → teal'],
	['percy', 'SILHOUETTE', '#9E66BF', '.percy.yml', 'brand #9E66BF'],
	['phpcsfixer', 'SILHOUETTE', '#6A7BC8', '.php-cs-fixer.php', 'php #6A7BC8 (R3 rhyme)'],
	['phraseapp', 'SILHOUETTE', '#3E93C4', '.phraseapp.yml', 'no brand → globe blue'],
	['pm2', 'BADGE', '#2C30B9', 'ecosystem.config.js', 'brand indigo → #2C30B9'],
	['pm2-ecosystem', 'SILHOUETTE', '#6A6EE0', 'ecosystem.config.cts', 'pm2 indigo (R3 sibling)'],
	['postcssconfig', 'SILHOUETTE', '#D0942F', '.postcssrc', 'postcss #D0942F (R3 rhyme)'],
	['posthtml', 'BADGE', '#D18A5E', '.posthtmlrc', 'no brand → warm ochre'],
	['preact', 'SILHOUETTE', '#8A5CD6', 'preact.config.js', 'brand #673AB8 ↑ #8A5CD6'],
	['precommit', 'SILHOUETTE', '#8E9E4E', '.pre-commit-config.yaml', 'no brand → olive'],
	['prefect', 'SILHOUETTE', '#3E63D0', 'prefect.toml', 'brand blue → #3E63D0'],
	['procfile', 'SILHOUETTE', '#8455CE', 'Procfile', 'heroku violet (R3 sibling)'],
	['protractor', 'SILHOUETTE', '#C43E5E', 'protractor.conf.js', 'no brand → Angular-adjacent rose']
];
